#!/bin/bash

export VISUAL=vim
export EDITOR="$VISUAL"
export PYTHONIOENCODING=UTF-8

export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export LC_ALL="en_US.UTF-8"
alias vi=vim



#export GITAWAREPROMPT=~/.bash/git-aware-prompt
#source "${GITAWAREPROMPT}/main.sh"

ORIG_PS1=$PS1

prompt() {
    PS1="$(powerline-rs --shell bash $?)"
}
PROMPT_COMMAND=prompt


[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*




alias sl="/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl"
export PATH="$PATH:$HOME/.composer/vendor/bin"
alias fl="bundle exec fastlane"



export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"


# Allow us to use Ctrl-s and Ctrl-q as keybinds
stty -ixon
if [ -e /Users/hja/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/hja/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
export PATH=/snap/bin:$PATH

export PATH=$HOME/.local/bin/emrichen:$PATH:~/.local/bin/


export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash

export PATH=/usr/local/bin:/usr/local/go/bin:$PATH

# Predictable SSH authentication socket location.
SOCK="/tmp/ssh-agent-$USER-screen"
if test $SSH_AUTH_SOCK && [ $SSH_AUTH_SOCK != $SOCK ]
then
    rm -f /tmp/ssh-agent-$USER-screen
    ln -sf $SSH_AUTH_SOCK $SOCK
    export SSH_AUTH_SOCK=$SOCK
fi
if [ -e /Users/hjanuschka/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/hjanuschka/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
source "$HOME/.cargo/env"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
